import {
  Add01Icon,
  Alert02Icon,
  Calendar03Icon,
  Cancel01Icon,
  Clock01Icon,
  Copy01Icon,
  Cursor01Icon,
  Delete02Icon,
  ExpandIcon,
  GridViewIcon,
  Layers01Icon,
  Link01Icon,
  Logout01Icon,
  Message01Icon,
  Pen01Icon,
  RefreshIcon,
  Search01Icon,
  SearchRemoveIcon,
  Settings02Icon,
  SidebarLeftIcon,
  TableIcon,
  Tag01Icon,
  Tick02Icon,
  UndoIcon,
  UserIcon,
} from "@hugeicons/core-free-icons";

// one icon per concept so the sidebar, palette, buttons and demos can never
// disagree. a recurring concept goes through here, one-off decoration
// (a rocket in a demo) stays a direct hugeicons import
export const APP_ICONS = {
  showcase: Cursor01Icon,
  table: TableIcon,
  blocks: Layers01Icon,
  chat: Message01Icon,
  showcaseCard: GridViewIcon,
  confirm: Tick02Icon,
  close: Cancel01Icon,
  remove: Delete02Icon,
  copy: Copy01Icon,
  edit: Pen01Icon,
  add: Add01Icon,
  expand: ExpandIcon,
  search: Search01Icon,
  searchEmpty: SearchRemoveIcon,
  link: Link01Icon,
  reload: RefreshIcon,
  settings: Settings02Icon,
  sidebar: SidebarLeftIcon,
  user: UserIcon,
  warning: Alert02Icon,
  time: Clock01Icon,
  calendar: Calendar03Icon,
  undo: UndoIcon,
  logout: Logout01Icon,
  tag: Tag01Icon,
} as const;
